name: iris_db
version: 0.0.4
description: A json DB.
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0'

dependencies:
  file: ^6.1.2
  path: ^1.8.2
  g_json: ^4.1.0    # 4.0.0

dev_dependencies:
  test: ^1.21.4
