name: iris_db
version: 0.1.3
description: A json DB (Database), support web.
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  file: ^7.0.0
  path: 1.8.3
  g_json: 4.1.0

dev_dependencies:
  test: ^1.24.9
