name: iris_db
version: 0.0.1
description: A json DB.
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  file: ^6.1.2
  g_json: ^4.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
