name: iris_db
version: 0.0.6+1
description: A json DB, support web.
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0'

dependencies:
  file: 6.1.4
  path: 1.8.3
  g_json: 4.1.0

dev_dependencies:
  test: ^1.23.1
